version: "3.8"
services:
  firefox:
    container_name: jlesage_firefox
    image: jlesage/firefox
    build: .
    security_opt:
      - seccomp:unconfined
    ports:
      - "5800:5800"
      - "5900:5900"
    volumes:
      - "./config:/config:rw"
    shm_size: 4gb
    environment:
      USER_ID: 1000
      GROUP_ID: 1000
      SUP_GROUP_IDS:
      UMASK:
      TZ: Etc/UTC
      KEEP_APP_RUNNING: 1
      APP_NICENESS:
      CLEAN_TMP_DIR: 1
      DISPLAY_WIDTH: 1280
      DISPLAY_HEIGHT: 768
      SECURE_CONNECTION: 1
      X11VNC_EXTRA_OPTS:
      ENABLE_CJK_FONT: 0
